### ISSUE TITLE
Thank you for sharing!

### ISSUE THREAD

**Issue by EugenMayer** [pburkholder/docker-concourse-vault#1]
Thank you for sharing this, it helped me a lot.

I basically used it to create a full automation here https://github.com/EugenMayer/docker-image-concourse-configurator - i switched to client-cert mode since that is recommended and also better to configure in an automation

more specifically here https://github.com/EugenMayer/docker-image-concourse-configurator/blob/master/bin/vault_init.sh

This way a concourse-server can be started right away, without any configuration or makefile, including direct vault support:
https://github.com/EugenMayer/concourseci-server-boilerplate or maybe just the vault part https://github.com/EugenMayer/concourseci-server-boilerplate/blob/master/docker-compose-vault.yml

so doing a 

    docker-compose up

Will setup a concourse including vault, right out working.

Again, thank you for your starting point!

**Comment by pburkholder** [comment]
My pleasure! Thanks for leaving a note.
